### ISSUE TITLE
The animation for the Moinesse fighter female human should be moved to a WQL paletted slot

### ISSUE THREAD

**Issue by eyre-j** [GwendolyneFreddy/Infinity-Animations#3]
The MOINESSE_FIGHTER_FEMALE_HUMAN currently resides at 0x6846, which is designated as a WQN paletted slot. In game, this exhibits some problems. The most obvious is that during an attack, the weapon appears below the point at which the character should be holding it, making it seem as if it were attacking while not being held at all. This is particularly apparent when wielding two handed weapons. Additionally, items equipped in inventory are not rendered at the appropriate places on the paper doll.

If MOINESSE_FIGHTER_FEMALE_HUMAN is moved to a WQL paletted slot, this issue is resolved. I tested this by modifying the t-animate.tpa and t-anisnd.tpa files to use the 0x684d slot (and renaming the associated BAMs) in version 5 of IA. The result was that weapon animations appear properly wielded in the character's hands, and paper doll items are rendered appropriately.

**Comment by GwendolyneFreddy** [comment]
Which game are you  playing? I guess it is a EE version.
Because moinesse animations for IA were designed to fit the specific IA character animation type which is a bit different from the vanilla one.

Excerpt from IA documentation:
"_This animation type differs from the one used for the original game files in that I've decided not to split the G animation series. It's exactly the same content, just kept in one file (see BGII SPLIT/BGII UNSPLIT). Essentially, if you'd like a duplicate or edit of a current character animation, you will have to join the G1 G11 G12... files into a single G1 file. This is done mainly to save override clutter (and makes it easier to create content to boot).

If you'd like to have an animation using existing object animations (e.g. because it's an edit of an existing animation), choose one of the CHARACTER BGII WQM/L/N/S animation slots with the desired size category_"

The repo does not contain yet the t-animate-ee.tpa file that will install animations for EE games. And I am currently rebuilding moinesse animations to fit the original BGII character type used by EE games.

**Comment by Sampsca** [comment]
"And I am currently rebuilding moinesse animations to fit the original BGII character type used by EE games."
Need help?  I expect PS BAM would make this much easier and quicker than traditional methods (BAMWorkshop 1/2).

**Comment by eyre-j** [comment]
I play classic BG2/BGT. If you like I can upload screenshots for comparison.

**Comment by eyre-j** [comment]
I uploaded a couple of screen shots. Also note that the helmet animation is rendered incorrectly as well in both images.

![Moinesse_human_female_fighter_animation_bug](https://user-images.githubusercontent.com/81866990/114287095-39946180-9a32-11eb-9a31-2d628de36dca.png)
![Moinesse_human_female_fighter_inventory_bug](https://user-images.githubusercontent.com/81866990/114287098-3dc07f00-9a32-11eb-9891-6d0aba0c46f3.png)

Contents of my WeiDU.log:
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~TOBEX/TOBEX.TP2~ #0 #100 // TobEx - Core: v28
~TOBEX/TOBEX.TP2~ #0 #101 // Apply Concentration Check On Damage [WIP]: v28
~TOBEX/TOBEX.TP2~ #0 #102 // Awaken On Damage: v28
~TOBEX/TOBEX.TP2~ #0 #104 // Disable Stoneskin Grey Colour [C]: v28
~TOBEX/TOBEX.TP2~ #0 #105 // No Spell Interruption On Zero Damage: v28
~TOBEX/TOBEX.TP2~ #0 #106 // Use Caster Level On Mirror Image [C]: v28
~TOBEX/TOBEX.TP2~ #0 #107 // Allow All Races to Dual Class: v28
~TOBEX/TOBEX.TP2~ #0 #109 // Disable Experience Boost: v28
~TOBEX/TOBEX.TP2~ #0 #111 // Disable Silence On Charm: v28
~TOBEX/TOBEX.TP2~ #0 #112 // Level One Proficiency Restrictions: v28
~TOBEX/TOBEX.TP2~ #0 #113 // Remain Hidden On Pickpocket Success [C]: v28
~TOBEX/TOBEX.TP2~ #0 #115 // Dialogue Greeting Subtitles: v28
~TOBEX/TOBEX.TP2~ #0 #116 // Enable Animation Attack Sounds: v28
~TOBEX/TOBEX.TP2~ #0 #117 // Universal Four Inventory Weapon Slots: v28
~TOBEX/TOBEX.TP2~ #0 #118 // Subtitles For Standard Soundsets: v28
~TOBEX/TOBEX.TP2~ #0 #119 // Remove all race-class restrictions: v28
~TOBEX/TOBEX.TP2~ #0 #120 // Drop Inventory on Disintegrate: v28
~TOBEX/TOBEX.TP2~ #0 #121 // Drop Inventory on Frozen Death: v28
~TOBEX/TOBEX.TP2~ #0 #122 // Drop Inventory on Stone Death: v28
~TOBEX/TOBEX.TP2~ #0 #123 // Enable Auto-Pause On All Screens: v28
~TOBEX/TOBEX.TP2~ #0 #124 // Make All Attack Animations Genuine Attacks: v28
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #1001 // BG2 Fixpack - Game Text Update -> GTU Classic (from Baldurdash, by Kevin Dorner): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #3 // BETA Core Fixes (please check the readme!): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #100 // Party Gets XP for Sending Keldorn to Reconcile With Maria: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #101 // Improved Spell Animations: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #103 // Mixed-Use Dagger Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #104 // Ghreyfain's Holy Symbol Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #106 // Giants Receive Penalties When Attacking Halflings, Dwarves, and Gnomes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #107 // Remove Dual-Classing Restriction from Archers and Stalkers: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #109 // Corrected Summoned Demon Behavior: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #110 // Additional Script Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #111 // Bard Song Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #112 // Wizard Slayers Cause Miscast Magic on Ranged Attacks: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #113 // Additional Alignment Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #114 // Change Free Action to Protect Against Stun: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #115 // Paws from Shapeshifting Can Not Be Dispelled: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #116 // Remove Thieving Start Bonuses from Bard and Ranger Skills: v13
~1PP/1PP.TP2~ #0 #101 // 1ppv4: Core paperdolls (main component): v4.2.0
~1PP/1PP.TP2~ #0 #103 // 1ppv4: Extended palette entries -> Full install (recommended): v4.2.0
~1PP/1PP.TP2~ #0 #104 // 1ppv4: GUI additions for BGII: v4.2.0
~1PP/1PP.TP2~ #0 #105 // 1ppv4: Avatar fixes: v4.2.0
~1PP/1PP.TP2~ #0 #106 // 1ppv4: Female Dwarves -> Separate Avatars for Female Dwarves - Baldur's Gate II: v4.2.0
~1PP/1PP.TP2~ #0 #111 // 1ppv4: Thieves Galore -> BGII - Unique Thief Avatars: v4.2.0
~1PP/1PP.TP2~ #0 #114 // 1ppv4: Softer Spell Effects: v4.2.0
~1PP/1PP.TP2~ #0 #200 // 1ppv4: Core content patches: v4.2.0
~1PP/1PP.TP2~ #0 #201 // 1ppv4: Consistent spell and scroll icons: v4.2.0
~1PP/1PP.TP2~ #0 #202 // 1ppv4: Spell tweaks: v4.2.0
~1PP/1PP.TP2~ #0 #203 // 1ppv4: Restored flame sword animations: v4.2.0
~1PP/1PP.TP2~ #0 #204 // 1ppv4: Colourable Quarterstaves: v4.2.0
~1PP/1PP.TP2~ #0 #205 // 1ppv4: Legacy Shields: v4.2.0
~1PP/1PP.TP2~ #0 #206 // 1ppv4: Additional Shield Animations (core): v4.2.0
~1PP/1PP.TP2~ #0 #207 // 1ppv4: Wizards' Staves (core): v4.2.0
~1PP/1PP.TP2~ #0 #208 // 1ppv4: Additional Helmet Animations (core): v4.2.0
~1PP/1PP.TP2~ #0 #209 // 1ppv4: Attachable wings (core): v4.2.0
~1PP/1PP.TP2~ #0 #210 // 1ppv4: Increased paperdoll object variety (core): v4.2.0
~1PP/1PP.TP2~ #0 #400 // 1ppv4: Core updates and item patches: v4.2.0
~1PP/1PP.TP2~ #0 #401 // 1ppv4: Improved projectile effects: v4.2.0
~1PP/1PP.TP2~ #0 #300 // 1ppv4: Fixed animations for solars and elementals: v4.2.0
~1PP/1PP.TP2~ #0 #301 // 1ppv4: Miscellaneous content fixes: v4.2.0
~INFINITYANIMATIONS/SETUP-INFINITYANIMATIONS.TP2~ #0 #0 // Infinity Animations: v5 BWP Fix
~INFINITYANIMATIONS/SETUP-INFINITYANIMATIONS.TP2~ #0 #25 // Humanoid Animation Fixes: v5 BWP Fix
~INFINITYANIMATIONS/SETUP-INFINITYANIMATIONS.TP2~ #0 #9000 // Fix Areas -> Creature References: v5 BWP Fix
```

**Comment by eyre-j** [comment]
I'm not sure if this matters, but I set the animation to the Moinesse version via ShadowKeeper.

**Comment by GwendolyneFreddy** [comment]
It is not a good idea to use moinesse avatars with characters because they have not been designed for this purpose, hence the paperdoll glitches.
Anyway, I could reproduce this bug, which was also occurring with all moinesse_female_human animations and fixed them locally.
Thanks for reporting. :wink:

**Comment by GwendolyneFreddy** [comment]
@Sampsca 
"'And I am currently rebuilding moinesse animations to fit the original BGII character type used by EE games.'
Need help? I expect PS BAM would make this much easier and quicker than traditional methods (BAMWorkshop 1/2)."

I have not been using BAMWorkshop tools for a while and rather use NI BAM Converter.
If you have time, yes, I would appreciate your help. I already rebuilt 6 of them, but did not have time to test them. If your PSBAM  tool can easily automate the process, fell free to rebuild all of them!

On another hand, if you can fix the g2 white Ellesime red hair color bug easily, it would be cool because as far as I investigates, g1 and g2 files don't use the same palette, and it is quite impossible to change hair pixels by hand...

**Comment by GwendolyneFreddy** [comment]
@eyre-j If you want to benefit from all 1PP paperdoll content, you must install IA BG1 Characters components before 1pp.

**Comment by Sampsca** [comment]
@GwendolyneFreddy
I'm struggling to come up with an acceptable solution for the Ellesime issue, but I have a couple ideas left to try.  As to the IA vs BGII character animation formats, can's you just make copies of G1 and rename them G11 thru G19 and everything will work?
